const fakeData = [
  {
    id: '1',
    firstName: ' نام اول نام اول نام اول نام اول نام اول',
    lastName: 'نام خانوادگی اول',
    country: 'ایران',
    city: 'طهران',
    age: 33,
    dateOfBirth: '2020/01/18',
    progress: 67,
  },
  {
    id: '2',
    firstName: 'نام دوم',
    lastName: 'نام خانوادگی دوم',
    country: 'ایران',
    city: 'طهران',
    age: 27,
    dateOfBirth: '2018/05/22',
    progress: 90,
  },
  {
    id: '3',
    firstName: 'نام سوم',
    lastName: 'نام خانوادگی سوم',
    country: 'ایران',
    city: 'طهران',
    age: 50,
    dateOfBirth: '2008/11/02',
    progress: 100,
  },
  {
    id: '4',
    firstName: 'نام چهارم',
    lastName: 'نام خانوادگی چهارم',
    country: 'ایران',
    city: 'طهران',
    age: 50,
    dateOfBirth: '2008/11/02',
    progress: 100,
  },
  {
    id: '5',
    firstName: 'نام پنجم',
    lastName: 'نام خانوادگی پنجم',
    country: 'ایران',
    city: 'طهران',
    age: 50,
    dateOfBirth: '2008/11/02',
    progress: 100,
  },
  {
    id: '6',
    firstName: 'نام ششم',
    lastName: 'نام خانوادگی ششم',
    country: 'ایران',
    city: 'طهران',
    age: 50,
    dateOfBirth: '2008/11/02',
    progress: 100,
  },
  {
    id: '7',
    firstName: 'نام هفتم',
    lastName: 'نام خانوادگی هفتم',
    country: 'ایران',
    city: 'طهران',
    age: 50,
    dateOfBirth: '2008/11/02',
    progress: 100,
  },
  {
    id: '8',
    firstName: 'نام هشتم',
    lastName: 'نام خانوادگی هشتم',
    country: 'ایران',
    city: 'طهران',
    age: 50,
    dateOfBirth: '2008/11/02',
    progress: 100,
  },
  {
    id: '9',
    firstName: 'نام نهم',
    lastName: 'نام خانوادگی نهم',
    country: 'ایران',
    city: 'طهران',
    age: 50,
    dateOfBirth: '2008/11/02',
    progress: 100,
  },
];

export default fakeData;
