export const teamUsers = [
  {
    UserId: '1',
    Name: 'خشایار جهانیان',
    Email: 'khashayar.jahanian@gmail.com',
    ProfileUrl: 'https://picsum.photos/200',
    IsAdmin: true,
    lastDate: '1399/8/15',
    lastTime: '23:26',
    IsOnline: false,
  },
  {
    UserId: '1',
    Name: 'رامین یاوری',
    Email: 'sirraminyavari@gmail.com',
    ProfileUrl: 'https://picsum.photos/200',
    IsAdmin: true,
    lastDate: '1399/8/15',
    lastTime: '23:26',
    IsOnline: false,
  },
  {
    UserId: '1',
    Name: 'سپهر ملازاده',
    Email: 'sepehr.mollazaeh@gmail.com',
    ProfileUrl: 'https://picsum.photos/200',
    IsAdmin: false,
    lastDate: '1399/8/15',
    lastTime: '23:26',
    IsOnline: false,
  },
  {
    UserId: '1',
    Name: 'امیرحسین سیف',
    Email: 'amirhossein.seyf@gmail.com',
    ProfileUrl: 'https://picsum.photos/200',
    IsAdmin: false,
    lastDate: '1399/8/15',
    lastTime: '23:26',
    IsOnline: false,
  },
  {
    UserId: '1',
    Name: 'رسول حسامی رستمی',
    Email: 'rasoul@gmail.com',
    ProfileUrl: 'https://picsum.photos/200',
    IsAdmin: false,
    lastDate: '1399/8/15',
    lastTime: '23:26',
    IsOnline: false,
  },
  {
    UserId: '1',
    Name: 'علی کارگر',
    Email: 'ali.kargar@gmail.com',
    ProfileUrl: 'https://picsum.photos/200',
    IsAdmin: false,
    lastDate: '1399/8/15',
    lastTime: '23:26',
    IsOnline: false,
  },
  {
    UserId: '1',
    Name: 'مهدی خلفی',
    Email: 'mehdi.kh14.2@gmail.com',
    ProfileUrl: 'https://picsum.photos/200',
    IsAdmin: false,
    lastDate: '1399/8/15',
    lastTime: '23:26',
    IsOnline: false,
  },
  {
    UserId: '1',
    Name: 'رضا نجفی',
    Email: 'reza.najafi@gmail.com',
    ProfileUrl: 'https://picsum.photos/200',
    IsAdmin: false,
    lastDate: '1399/8/15',
    lastTime: '23:26',
    IsOnline: false,
  },
  {
    UserId: '1',
    Name: 'مهدی موسوی',
    Email: 'musavi.mehdi@outlook.com',
    ProfileUrl: 'https://picsum.photos/200',
    IsAdmin: false,
    lastDate: '1399/8/15',
    lastTime: '23:26',
    IsOnline: false,
  },
];

export const invitedUsers = [
  {
    UserId: '1',
    Name: 'ابوالفضل پورعرب',
    Email: 'poorarab@gmail.com',
    invitationDate: '1399/8/15',
    invitationTime: '23:26',
  },
  {
    UserId: '1',
    Name: 'فریبرز عرب نیا',
    Email: 'arabnia@gmail.com',
    invitationDate: '1399/8/15',
    invitationTime: '23:26',
  },
  {
    UserId: '1',
    Name: 'علی دایی',
    Email: 'ali.daei@gmail.com',
    invitationDate: '1399/8/15',
    invitationTime: '23:26',
  },
];
