const headers = [
  {
    id: '0',
    title: '',
    accessor: 'rowIAction',
    dataType: 'action',
    options: {
      editable: false,
      width: 30,
      disableSortBy: true,
    },
  },
  {
    id: '1',
    title: '#',
    accessor: 'rowIndex',
    dataType: 'index',
    options: {
      editable: false,
      width: 40,
      disableSortBy: true,
    },
  },
  {
    id: '2',
    title: 'عنوان',
    accessor: 'title',
    dataType: 'string',
    options: {
      editable: true,
      isRequired: true,
      maxWidth: 200,
    },
  },
  {
    id: '3',
    title: 'نوع نامه',
    accessor: 'docType',
    dataType: 'single-select',
    options: { editable: true, disableSortBy: true },
  },
  {
    id: '4',
    title: 'واحدهای مرتبط با نامه',
    accessor: 'relatedIndustry',
    dataType: 'multi-select',
    options: { editable: true, disableSortBy: true },
  },
  {
    id: '5',
    title: 'تاریخ بازنگری سند',
    accessor: 'revisionDate',
    dataType: 'date',
    options: { editable: true, minWidth: 170 },
  },
  {
    id: '6',
    title: 'شماره نامه',
    accessor: 'docNumber',
    dataType: 'number',
    options: { editable: true, minWidth: 100 },
  },
  {
    id: '7',
    title: 'گیرنده نامه',
    accessor: 'place',
    dataType: 'binary',
    options: { editable: true, disableSortBy: true, isRequired: true },
  },
  {
    id: '8',
    title: 'رونوشت برای کاربر',
    accessor: 'user',
    dataType: 'user',
    options: { editable: true, disableSortBy: true, maxWidth: 200 },
  },
  {
    id: '9',
    title: 'موضوع نامه',
    accessor: 'topic',
    dataType: 'node',
    options: { editable: true, disableSortBy: true, maxWidth: 200 },
  },
  {
    id: '10',
    title: 'فایل نامه',
    accessor: 'microsoftFile',
    dataType: 'file',
    options: { editable: true, disableSortBy: true, maxWidth: 200 },
  },
  {
    id: '11',
    title: 'اطلاعات ثبت',
    accessor: 'recordInfo',
    dataType: 'RecordInfo',
    options: { editable: true, minWidth: 220 },
  },
];

export default headers;
