import SubjectItem from 'components/SubjectItem/screen/SubjectItem';

const { RVGlobal } = window;
const avatar = RVGlobal?.CurrentUser?.ProfileImageURL;
const list = [
  {
    AdditionalID: 'MTAyOA==',
    Archived: false,
    ChildsCount: 0,
    CreationDate: '1399/07/13',
    Creator: {
      UserID: '6b9e8414-c1ea-4e59-8aa8-34b4bceb74e7',
      UserName: 'YWRtaW4=',
      FirstName: '2YXZh9iv24w=',
      LastName: '2K7ZhNmB24w=',
      ProfileImageURL: avatar,
    },
    Description: '',
    ExpertsCount: 0,
    Extensions: [],
    HasChild: false,
    HideCreators: false,
    IconURL: '../../images/Preview.png',
    LikeStatus: false,
    LikesCount: 0,
    MembersCount: 0,
    Name: '2qnYp9ix2KjYsdivINiv2KfYr9mHINmF2K3ZiNix24wg2K/YsSDZgdix2YjYtA==',
    NodeID: 'aa9e3dbb-df98-4b03-8f46-e3d9fb4a762b',
    NodeType: '2YXYrdmI2LEg2YXYrdiq2YjYpw==',
    NodeTypeID: '6261f696-2432-4307-9813-5288f231e24c',
    RelatedNodesCount: 0,
    Service: {},
    Status: '',
    UserStatus: {
      Editable: false,
      IsAdminMember: false,
      IsAreaAdmin: false,
      IsContributor: false,
      IsCreator: false,
      IsExpert: false,
      IsMember: false,
      IsServiceAdmin: false,
    },
    VisitsCount: 0,
    WFState: '',
  },
  {
    AdditionalID: 'MTAyOA==',
    Archived: false,
    ChildsCount: 0,
    CreationDate: '1399/07/13',
    Creator: {
      UserID: '6b9e8414-c1ea-4e59-8aa8-34b4bceb74e7',
      UserName: 'YWRtaW4=',
      FirstName: '2YXZh9iv24w=',
      LastName: '2K7ZhNmB24w=',
      ProfileImageURL: avatar,
    },
    Description: '',
    ExpertsCount: 0,
    Extensions: [],
    HasChild: false,
    HideCreators: false,
    IconURL: '../../images/Preview.png',
    LikeStatus: false,
    LikesCount: 0,
    MembersCount: 0,
    Name: '2qnYp9ix2KjYsdivINiv2KfYr9mHINmF2K3ZiNix24wg2K/YsSDZgdix2YjYtA==',
    NodeID: 'aa9e3dbb-df98-4b03-8f46-e3d9fb4a762b',
    NodeType: '2YXYrdmI2LEg2YXYrdiq2YjYpw==',
    NodeTypeID: '6261f696-2432-4307-9813-5288f231e24c',
    RelatedNodesCount: 0,
    Service: {},
    Status: '',
    UserStatus: {
      Editable: false,
      IsAdminMember: false,
      IsAreaAdmin: false,
      IsContributor: false,
      IsCreator: false,
      IsExpert: false,
      IsMember: false,
      IsServiceAdmin: false,
    },
    VisitsCount: 0,
    WFState: '',
  },
  {
    AdditionalID: 'MTAyOA==',
    Archived: false,
    ChildsCount: 0,
    CreationDate: '1399/07/13',
    Creator: {
      UserID: '6b9e8414-c1ea-4e59-8aa8-34b4bceb74e7',
      UserName: 'YWRtaW4=',
      FirstName: '2YXZh9iv24w=',
      LastName: '2K7ZhNmB24w=',
      ProfileImageURL: avatar,
    },
    Description: '',
    ExpertsCount: 0,
    Extensions: [],
    HasChild: false,
    HideCreators: false,
    IconURL: '../../images/Preview.png',
    LikeStatus: false,
    LikesCount: 0,
    MembersCount: 0,
    Name: '2qnYp9ix2KjYsdivINiv2KfYr9mHINmF2K3ZiNix24wg2K/YsSDZgdix2YjYtA==',
    NodeID: 'aa9e3dbb-df98-4b03-8f46-e3d9fb4a762b',
    NodeType: '2YXYrdmI2LEg2YXYrdiq2YjYpw==',
    NodeTypeID: '6261f696-2432-4307-9813-5288f231e24c',
    RelatedNodesCount: 0,
    Service: {},
    Status: '',
    UserStatus: {
      Editable: false,
      IsAdminMember: false,
      IsAreaAdmin: false,
      IsContributor: false,
      IsCreator: false,
      IsExpert: false,
      IsMember: false,
      IsServiceAdmin: false,
    },
    VisitsCount: 0,
    WFState: '',
  },
  {
    AdditionalID: 'MTAyOA==',
    Archived: false,
    ChildsCount: 0,
    CreationDate: '1399/07/13',
    Creator: {
      UserID: '6b9e8414-c1ea-4e59-8aa8-34b4bceb74e7',
      UserName: 'YWRtaW4=',
      FirstName: '2YXZh9iv24w=',
      LastName: '2K7ZhNmB24w=',
      ProfileImageURL: avatar,
    },
    Description: '',
    ExpertsCount: 0,
    Extensions: [],
    HasChild: false,
    HideCreators: false,
    IconURL: '../../images/Preview.png',
    LikeStatus: false,
    LikesCount: 0,
    MembersCount: 0,
    Name: '2qnYp9ix2KjYsdivINiv2KfYr9mHINmF2K3ZiNix24wg2K/YsSDZgdix2YjYtA==',
    NodeID: 'aa9e3dbb-df98-4b03-8f46-e3d9fb4a762b',
    NodeType: '2YXYrdmI2LEg2YXYrdiq2YjYpw==',
    NodeTypeID: '6261f696-2432-4307-9813-5288f231e24c',
    RelatedNodesCount: 0,
    Service: {},
    Status: '',
    UserStatus: {
      Editable: false,
      IsAdminMember: false,
      IsAreaAdmin: false,
      IsContributor: false,
      IsCreator: false,
      IsExpert: false,
      IsMember: false,
      IsServiceAdmin: false,
    },
    VisitsCount: 0,
    WFState: '',
  },
  {
    AdditionalID: 'MTAyOA==',
    Archived: false,
    ChildsCount: 0,
    CreationDate: '1399/07/13',
    Creator: {
      UserID: '6b9e8414-c1ea-4e59-8aa8-34b4bceb74e7',
      UserName: 'YWRtaW4=',
      FirstName: '2YXZh9iv24w=',
      LastName: '2K7ZhNmB24w=',
      ProfileImageURL: avatar,
    },
    Description: '',
    ExpertsCount: 0,
    Extensions: [],
    HasChild: false,
    HideCreators: false,
    IconURL: '../../images/Preview.png',
    LikeStatus: false,
    LikesCount: 0,
    MembersCount: 0,
    Name: '2qnYp9ix2KjYsdivINiv2KfYr9mHINmF2K3ZiNix24wg2K/YsSDZgdix2YjYtA==',
    NodeID: 'aa9e3dbb-df98-4b03-8f46-e3d9fb4a762b',
    NodeType: '2YXYrdmI2LEg2YXYrdiq2YjYpw==',
    NodeTypeID: '6261f696-2432-4307-9813-5288f231e24c',
    RelatedNodesCount: 0,
    Service: {},
    Status: '',
    UserStatus: {
      Editable: false,
      IsAdminMember: false,
      IsAreaAdmin: false,
      IsContributor: false,
      IsCreator: false,
      IsExpert: false,
      IsMember: false,
      IsServiceAdmin: false,
    },
    VisitsCount: 0,
    WFState: '',
  },
];
const IntroNodes = ({ selectMode, liteMode, onChecked }) => {
  return (
    <div
      style={{
        height: '100%',
        width: '100%',
        flex: 1,
      }}>
      {list.map((x, index) => {
        return (
          <SubjectItem
            key={index}
            selectMode={selectMode}
            liteMode={liteMode}
            onChecked={onChecked}
            parentNodeType={'6261f696-2432-4307-9813-5288f231e24c'}
            item={x}
            isSaas={false}
            onReload={() => console.log('onReload')}
            onBookmark={() => console.log('onBookmark')}
          />
        );
      })}
    </div>
  );
};

export default IntroNodes;
