name: check for project build errors

on:
  pull_request:
    branches:
      - dev

jobs:
  code-structure-test:
    runs-on: ${{ matrix.os }}
    env:
      CI: false
    strategy:
      matrix:
        os: [windows-latest]
        node: [16]
    env:
      CI: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: install project dependencies
        run: npm install

      - name: Build project package
        run: npm run build

      - name: Build JSDoc
        run: npm run docs

      - name: Build StoryBook.js
        run: npm run build-storybook
