name: check for project build errors

on:
  pull_request:
    branches:
      - dev

jobs:
  code-structure-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    env:
      CI: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://npm.pkg.github.com'
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: install project dependencies
        run: yarn install

      - name: Build project package
        run: yarn run build

      - name: Build JSDoc
        run: yarn run docs

      # - name: Initialize StoryBook and install dependencies
      #   run: yarn add -D @etchteam/storybook-addon-css-variables-theme@^1.1.1 @storybook/addon-actions@^6.4.18 @storybook/addon-docs@^6.4.18 @storybook/addon-essentials@^6.4.18 @storybook/addon-links@^6.4.18 @storybook/node-logger@^6.4.18 @storybook/preset-create-react-app@^3.2.0 @storybook/react@^6.4.18

      # - name: Build StoryBook.js
      #   run: yarn run build-storybook
